#!/bin/bash
set -eux -o pipefail

repo=$1
ref=$2
platform=$3
mppyaml=$4
path=$5
filename=$(basename "$path")

workdir=$PWD

# Since it doesn't exist create loop-control
mknod /dev/loop-control c 10 237

# get away from the virtiofs share because the xattrs that
# are written out by the ostree deploy will cause SELinux denials.
# Tell osbuild to write out artifacts into a file in the root
# filesystem of the supermin VM, which is ephemeral.
mkdir /var/osbuild
outdir=/var/osbuild/out

#git clone https://github.com/ravanelli/osbuild.git --branch bootupd 

# Run through the preprocessor
./osbuild/tools/osbuild-mpp                         \
    -D ref=\""${ref}"\"             \
    -D repourl=\""file://${repo}"\" \
    -D filename=\""${filename}"\"   \
    "${mppyaml}"                    \
    processed.json

# Build the image
python3 -m osbuild --libdir ./osbuild \
    --out "$outdir"            \
    --store cache/osbuild/store/ \
    --cache-max-size 9GiB        \
    --checkpoint tree            \
    --checkpoint raw-image       \
    --export "$platform" processed.json


# Copy it out to the specified location
cp "${outdir}/${platform}/${filename}" "${path}"
